language:
  - python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - 3.5-dev
  - '3.6'
  - 3.6-dev
  - 3.7-dev
  - nightly
before_install:
  - sudo apt-get install sleuthkit
install:
  - sudo pip install wheel codecov
  - sudo python setup.py install
script:
  - sh tests/tests.sh
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  user: poorbillionaire
  password:
    secure: AAFYKxkzQjP/qL5uLqW2U15EN6y+1utplosctCMz5Glc+r7Fo9rKnijqXgDCDbFd5TBVGx8T3b2YlwpB+DyEgIvCaJswP5VpllwaZeTrDH83Muz1IhY0Qd5rhPLzxcBKcZSPF60EKhFokj9snjxBMjEAb/lMO/MHQJ20uqh2n31+1KD6aZfngU2W5MJSI7Py5spDp1sPKVbHUpVn5vJmIvqENeIdtgsyG41LDDLdCyMawSonlFCjKcJUx0SYMH+RMYPD5P2/Qf24If/llE1q++hphBunlnD9CR76YzkF00tMzz0x8nMVDatGzrxZIzP8lRytm9OOee5Wx/NW2j97hB/M+JTRz89Q3adpMO9KVun/J+5c9KKRV6eeIDOTGG9gFaK37xBczzvUCjE0OLvK9KBpT8gPT03/EMYOiX52d0TXbvrCZ7E/WZkOfzgnoIxzHlSEsXW6L5+eatKZUT3aFH4pKlggf1K8qzhDwvq3S9Fy2y9yuWk1rVYo8LBW7Z/+WcCsJt7mY8CHfZIlowprgl8Pz/ziEq4XDmeu6cZzIZRi3Wy33vlWR0kzkK+YkOGdvsymZwaZGRYA9vzN7ni2eiTkhrECHHMqO0ojh0kRc8yLHquFIBRXwJTqzAfY6iwDng43LcAOHkBjqjfTeG3K4BLaVgLLddVVGWimjKTfF5s=
  on:
    branch: master
    python: 3.6
